"""added packages

Revision ID: 026fab68d528
Revises: 1c5d7cca137f
Create Date: 2019-11-28 23:10:27.575116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026fab68d528'
down_revision = '1c5d7cca137f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('attendees', sa.String(length=64), nullable=False),
    sa.Column('custom', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('avaiable_packages', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_type')
    )
    op.create_table('event_packages',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'package_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
