"""added image model

Revision ID: 105313561053
Revises: ba95f49eb1e0
Create Date: 2019-11-17 17:12:43.147036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105313561053'
down_revision = 'ba95f49eb1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_unique_constraint(None, 'users', ['website'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('images')
    # ### end Alembic commands ###
