"""saved events

Revision ID: 14adae5f3db7
Revises: 3c284e452936
Create Date: 2019-12-05 22:09:16.182978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14adae5f3db7'
down_revision = '3c284e452936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_events')
    # ### end Alembic commands ###
