"""imagetype

Revision ID: 1c5d7cca137f
Revises: 8f7cffacf31a
Create Date: 2019-11-24 22:35:12.380345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5d7cca137f'
down_revision = '8f7cffacf31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('events', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('events', sa.Column('pitch', sa.Text(), nullable=False))
    op.add_column('images', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('image_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'image_types', ['image_type_id'], ['id'])
    op.create_foreign_key(None, 'images', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'image_type_id')
    op.drop_column('images', 'event_id')
    op.drop_column('events', 'pitch')
    op.drop_column('events', 'description')
    op.drop_table('image_types')
    # ### end Alembic commands ###
