"""change Package model

Revision ID: 3732384e2748
Revises: 7e05beae1f3a
Create Date: 2019-12-14 20:11:57.637902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3732384e2748'
down_revision = '7e05beae1f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_event_package', 'events', ['event_id'], ['id'])
        batch_op.drop_column('deadline')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.drop_column('about_me')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.TEXT(), nullable=True))
        batch_op.drop_column('about')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint('fk_event_package', type_='foreignkey')
        batch_op.drop_column('event_id')

  
    # ### end Alembic commands ###
