"""remove user-image relationship

Revision ID: 3c284e452936
Revises: b884132df0ea
Create Date: 2019-12-02 22:55:49.479281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c284e452936'
down_revision = 'b884132df0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
