"""Removed has_paid column from users table

Revision ID: 616e5a8c7caf
Revises: ef93e0c4e552
Create Date: 2020-11-10 20:34:49.063484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616e5a8c7caf'
down_revision = 'ef93e0c4e552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_paid', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
