"""add video table

Revision ID: 76a4c99295d2
Revises: 0ca2f16ec665
Create Date: 2019-11-30 22:06:43.438379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a4c99295d2'
down_revision = '0ca2f16ec665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_url'), 'videos', ['url'], unique=True)
    op.create_index(op.f('ix_images_path'), 'images', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_path'), table_name='images')
    op.drop_index(op.f('ix_videos_url'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
