"""confirmation code

Revision ID: 7e05beae1f3a
Revises: ec9ec8b220ac
Create Date: 2019-12-12 22:44:31.270586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e05beae1f3a'
down_revision = 'ec9ec8b220ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('confirmation_code', ['confirmation_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.drop_constraint('confirmation_code', type_='unique')
        batch_op.drop_column('confirmation_code')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
