"""sponsorship amount

Revision ID: 80a38819d14c
Revises: bd65256f19d1
Create Date: 2020-01-13 16:11:15.670517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a38819d14c'
down_revision = 'bd65256f19d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=4, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
