"""venue address unique constraint

Revision ID: 8f7cffacf31a
Revises: 1ff19878e491
Create Date: 2019-11-22 22:38:00.160241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7cffacf31a'
down_revision = '1ff19878e491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_venues_address'), 'venues', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_address'), table_name='venues')
    # ### end Alembic commands ###
