"""has_paid

Revision ID: 96e2ef83ad93
Revises: 6b9047d3b757
Create Date: 2019-12-21 23:12:41.050551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e2ef83ad93'
down_revision = '6b9047d3b757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_paid', sa.Boolean(), nullable=True))
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('has_paid')

    # ### end Alembic commands ###
