"""added indexes

Revision ID: 98991d6d1bc3
Revises: 8a8781cb6acd
Create Date: 2020-02-09 20:09:38.865885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98991d6d1bc3'
down_revision = '8a8781cb6acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_end_datetime'), ['end_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_datetime'), ['start_datetime'], unique=False)

    with op.batch_alter_table('image_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_types_name'), ['name'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('has_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_company'), ['company'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_company'))
        batch_op.alter_column('has_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('image_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_types_name'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start_datetime'))
        batch_op.drop_index(batch_op.f('ix_events_end_datetime'))

    # ### end Alembic commands ###
