"""num_purchased

Revision ID: a578b9c0065b
Revises: 96e2ef83ad93
Create Date: 2020-01-09 21:23:52.955159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a578b9c0065b'
down_revision = '96e2ef83ad93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_purchased', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('num_purchased')

    # ### end Alembic commands ###
