"""remove custom field

Revision ID: af0ab7ee3fe2
Revises: 3732384e2748
Create Date: 2019-12-14 20:33:35.520350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0ab7ee3fe2'
down_revision = '3732384e2748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('custom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
