"""empty message

Revision ID: b884132df0ea
Revises: dfdbee893994
Create Date: 2019-12-02 19:23:52.421021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b884132df0ea'
down_revision = 'dfdbee893994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_url', table_name='videos')
    op.create_index(op.f('ix_videos_url'), 'videos', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_url'), table_name='videos')
    op.create_index('ix_videos_url', 'videos', ['url'], unique=1)
    # ### end Alembic commands ###
