"""updated user model

Revision ID: ba95f49eb1e0
Revises: 1b6f2b866d86
Create Date: 2019-11-16 19:05:31.021206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba95f49eb1e0'
down_revision = '1b6f2b866d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['website'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'website')
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
