"""metrics

Revision ID: bd65256f19d1
Revises: a578b9c0065b
Create Date: 2020-01-11 17:24:02.461873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd65256f19d1'
down_revision = 'a578b9c0065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('num_packages', sa.Integer(), nullable=False),
    sa.Column('num_packages_sold', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###
