"""update event model

Revision ID: c4724927a36d
Revises: 80a38819d14c
Create Date: 2020-01-22 23:43:13.880324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4724927a36d'
down_revision = '80a38819d14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('start_datetime')
        batch_op.drop_column('end_datetime')

    # ### end Alembic commands ###
