"""empty message

Revision ID: dfdbee893994
Revises: 76a4c99295d2
Create Date: 2019-12-01 22:00:33.967329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdbee893994'
down_revision = '76a4c99295d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['profile_photo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###
