"""remove sponsorship amount

Revision ID: fd5b0f09022f
Revises: b5505585c575
Create Date: 2020-01-26 20:32:53.063057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5b0f09022f'
down_revision = 'b5505585c575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=4, scale=2), nullable=False))

    # ### end Alembic commands ###
